# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10.4-slim-buster
RUN pip install --upgrade pip

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install cron


# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# ADD ./src/crontab /etc/cron.d/my-cron-file
# RUN chmod 0644 /etc/cron.d/my-cron-file
# RUN crontab /etc/cron.d/my-cron-file
# RUN touch /var/log/cron.log

# RUN addgroup -g 8877 -S viveorage && \
#  adduser -u 8877 -S viveorage -G viveorage

RUN useradd -m viveorange
USER viveorange

WORKDIR /home/viveorange

ADD --chown=viveorage:viveorage ./src/crontab ./
# RUN chmod 0644 ./crontab

# COPY ./src/*.py ./
# COPY ./src/*.sh ./
COPY --chown=viveorange:viveorange ./src/*.py ./
COPY --chown=viveorange:viveorange ./src/*.sh ./
RUN chmod 0700 ./lanzar_cron.sh


# Install pip requirements
# COPY requirements.txt ./
COPY --chown=viveorange:viveoragen requirements.txt ./
RUN python -m pip install --user -r requirements.txt

ENV PATH="/home/viveorage/.local/bin:${PATH}"
# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
# USER appuser

# RUN crontab -l | { cat; echo "* * * * * root bash /usr/app/src/lanzar_cron.sh"; } | crontab -
# RUN crontab /etc/cron.d/my-cron-file


# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["python", "./main.py"]
# CMD ["cron", "-f"]